# Generated by Django 5.1.1 on 2024-09-14 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('title', models.IntegerField()),
                ('interest', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('user', models.ManyToManyField(blank=True, related_name='investors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
