# Generated by Django 5.1.1 on 2024-09-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
