# Generated by Django 5.1.1 on 2024-09-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
    ]
