# Generated by Django 5.1.1 on 2024-09-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='image',
            field=models.ImageField(blank=True, upload_to='investment'),
        ),
    ]
