# Generated by Django 5.1.1 on 2024-09-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_investment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='eligible',
            field=models.BooleanField(default=False),
        ),
    ]
