# Generated by Django 5.1.1 on 2024-09-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_requested_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reffered',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
