# Generated by Django 5.1.1 on 2024-09-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_transaction_reffered'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
