# Generated by Django 5.1.1 on 2024-09-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_investment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
