# Generated by Django 5.1.1 on 2024-09-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_alter_requested_withdraw_options_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requested_withdraw',
            name='operator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
