# Generated by Django 5.1.1 on 2024-09-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_remove_game_user_game_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='today',
            field=models.BooleanField(default=False),
        ),
    ]
