# Generated by Django 5.1.1 on 2024-09-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_alter_investment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='image',
            field=models.ImageField(blank=True, null=True, storage='market.storage_backends.CustomMediaStorage', upload_to='investment/'),
        ),
    ]
