# Generated by Django 5.1.1 on 2024-09-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_alter_investment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
