# Generated by Django 5.1.1 on 2024-09-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_wallet_amount_from_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested_withdraw',
            name='messaged',
            field=models.BooleanField(default=False),
        ),
    ]
