# Generated by Django 5.1.1 on 2024-12-11 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_requested_withdraw_messaged'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='deposit_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='tier',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('allocated_tier_1_members', models.IntegerField()),
                ('allocated_tier_2_members', models.IntegerField()),
                ('allocated_tier_3_members', models.IntegerField()),
                ('tier_1_completed', models.BooleanField(default=False)),
                ('tier_2_completed', models.BooleanField(default=False)),
                ('tier_3_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
