# Generated by Django 5.1.1 on 2024-12-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_wallet_deposit_used_wallet_tier_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Profit', max_length=255)),
                ('amount_today', models.FloatField()),
                ('total_amount', models.FloatField()),
            ],
        ),
    ]
