# Generated by Django 5.1.1 on 2025-02-11 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_profit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposits', models.FloatField(default=0.0)),
                ('name', models.CharField(default='Pool', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='valid_for_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PoolParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pool',
            name='participants',
            field=models.ManyToManyField(through='market.PoolParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
