# Generated by Django 5.1.1 on 2025-02-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0027_pool_wallet_valid_for_pool_poolparticipant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolparticipant',
            name='deposit_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
