# Generated by Django 5.1.1 on 2025-04-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0028_poolparticipant_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='withdrawable',
            field=models.FloatField(default=0.0),
        ),
    ]
