# Generated by Django 5.1.1 on 2025-04-25 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0029_wallet_withdrawable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='image',
        ),
    ]
