# Generated by Django 5.1.1 on 2025-04-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0030_remove_transaction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='amount_bet',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='game',
            name='matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='selection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winnings',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='game',
            name='won',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='Lucky Draw', max_length=255),
        ),
    ]
