# Generated by Django 5.1.1 on 2025-05-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0032_alter_game_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='forced_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winning_numbers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='deposits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='poolparticipant',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='requested_withdraw',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
