# Generated by Django 5.1.1 on 2025-05-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0033_game_forced_reason_game_winning_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='game_track',
            field=models.FloatField(default=0.0),
        ),
    ]
