# Generated by Django 5.1.1 on 2024-09-14 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_referred_users_customer_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='referred_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
