# Generated by Django 5.1.1 on 2024-09-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customer_referred_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reference',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
