# Generated by Django 5.1.1 on 2024-09-15 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='referred_users',
        ),
        migrations.AddField(
            model_name='customer',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
