# Generated by Django 5.1.1 on 2024-09-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_referal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='referal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
