# Generated by Django 5.1.1 on 2024-12-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='recepient_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
