# Generated by Django 5.1.1 on 2025-01-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customer_recepient_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
