# Generated by Django 5.1.1 on 2025-04-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customer_paid_vendor_customer_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='affiliate',
            field=models.BooleanField(default=False),
        ),
    ]
