# Generated by Django 5.1.1 on 2025-04-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customer_affiliate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_played_lucky_draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='in_depletion_phase',
            field=models.BooleanField(default=False),
        ),
    ]
