# Generated by Django 5.1.1 on 2025-05-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customer_has_played_lucky_draw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_taken_referal_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
