# Generated by Django 5.1.1 on 2025-05-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_customer_has_taken_referal_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='has_taken_referal_bonus',
            new_name='has_played_coin_toss',
        ),
        migrations.AddField(
            model_name='customer',
            name='has_played_color_picker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_taken_coin_toss_referral_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_taken_color_picker_referral_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_taken_lucky_draw_referral_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
