# Generated by Django 5.1.1 on 2025-05-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_has_taken_referal_bonus_customer_has_played_coin_toss_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='has_played_coin_toss',
            new_name='has_had_first_game_win',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='has_played_color_picker',
            new_name='has_taken_referral_bonus',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='has_played_lucky_draw',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='has_taken_coin_toss_referral_bonus',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='has_taken_color_picker_referral_bonus',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='has_taken_lucky_draw_referral_bonus',
        ),
    ]
